name: publish
on: [push]
jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
    with:
      registry: ghcr.io
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build docker image
        run: |
          docker build . --tag ghcr.io/awesomelewis2007/light_builtins:latest
          docker run ghcr.io/awesomelewis2007/light_builtins:latest
          docker push ghcr.io/awesomelewis2007/light_builtins:latest