name: Test C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: make configure cpp tests
      run: make configure_cpp_test
    - name: make cpp tests
      run: make test_cpp
    - name: make configure c tests
      run: make configure_c_test
    - name: make c tests
      run: make test_c

